apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  namespace: default

data:
  redis-config:
    maxmemory 3mb
    maxmemory-policy allKey-lru 
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: cps-redis-pv-volume
  labels:
    type: local
    app: cps-redis
spec:
  storageClassName: local-storage
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/redis"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: cps-redis-claim
  labels:
    app: cps-redis
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: cps-redis
  name: cps-service
  namespace: default
spec:
  type: ClusterIP
  ports:
  - port:  6379
  selector:
    app: cps-redis

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    name: cps-redis
    component: cache
  name: cps-redis
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      name: cps-redis
  template:
    metadata:
      labels:
        name: cps-redis
        component: cache
    spec:
      containers:
      - name: cps-redis
        image: redis:latest
        ports:
        - containerPort: 6379
          name: cps-redis
        envFrom:
          - configMapRef:
              name: redis-config
        volumeMounts:
        - mountPath: /data/redis
          name: cps-redis-pv-volume
      volumes:
        - name: cps-redis-pv-volume
          persistentVolumeClaim:
            claimName: cps-redis-claim
