
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv-volume1
  labels:
    type: local
    app: cps-postgres-db
spec:
  storageClassName: standard
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/postgres"
---
apiVersion: v1
kind: persistentVolumeClaim
metadata:
  name: cps-postgres-db-claim
  labels:
    app: cps-postgres-db
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
