---
Version: apps/v1
kind: Deployment
metadata:
  name: cps-postgres-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cps-postgres-db
  template:
    metadata:
      labels:
        app: cps-postgres-db
    spec:
      containers:
        - name: postgres
          image: postgres:10.1
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: postgres-config
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: cps-postgres-db
      volumes:
        - name: cps-postgres-db
          persistentVolumeClaim:
            claimName: cps-postgres-db-claim
---

#apiVersion: v1
#kind: Service
#metadata:
 # name: postgres-service
#spec:
  #type: ClusterIP
  #selector:
   # app: cps-postgres-db
  #ports:
  #- name: tcp
   # port: 80
    #targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: cps-service
  labels:
    app: cps-postgres-db
  namespace: default
spec:
  type: NodePort
  ports:
  - port:  5432
  selector:
    app: cps-postgres-db

